use_frameworks!

target 'YLSegmentController_Example' do
  pod 'YLSegmentController', :path => '../'

  target 'YLSegmentController_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
